require: standard

AllCops:
  TargetRubyVersion: 3.0

inherit_gem:
  standard: config/base.yml
# Don't define any actual rubocop config here - this file is only used for
# proper editor support, and not used on CI, formatters, nor anywhere else.
